# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba2a64861b72a5cf9642fa9b90f6789553c97c898b0878dca30461c4d5db0d6e60a79f041826ec5d8f1fe116922e5cebdd4a4a990aa3998d725d54631e4f2b96

test:
  secret_key_base: 2c93dac4fab8587786cf1ad4c366f09d13b6078589c80bfc10e976c47907d587c7d02d27dcc4377e5e834ab25eb561e3e152cc0ed36f458ee9ea3c99a947f9dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
